Tester/CodeScene/Dental_Clinic_System/Dental_Clinic_System/Areas/Admin/Controllers/AdminAccountController.cs
using Dental_Clinic_System.Helper;
using Dental_Clinic_System.Models.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Dental_Clinic_System.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class AdminAccountController : Controller
	{
		private readonly DentalClinicDbContext _context;

		public AdminAccountController(DentalClinicDbContext context)
		{
			_context = context;
		}

		[HttpGet]
		public IActionResult Login(string returnUrl = "/Admin/Dashboard/Index")
		{
			ViewBag.ReturnUrl = returnUrl;
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Login(string username, string password)
		{
			var user = _context.Accounts.FirstOrDefault(d => username == d.Username && password == d.Password);
			if (user == null)
			{
				ViewBag.ErrorMessage = "Invalid username or password";
				return BadRequest("Sai Tên đăng nhập hoặc Mật khẩu");
			}

			if (user.Role == "Admin")
			{
				var claims = new List<Claim>
				{
					new Claim(ClaimTypes.Name, user.Username),
					new Claim(ClaimTypes.Role, user.Role)
				};

				var claimsIdentity = new ClaimsIdentity(claims, "GetAppointmentStatus");
				var authProperties = new AuthenticationProperties { IsPersistent = true };

				await HttpContext.SignInAsync("GetAppointmentStatus", new ClaimsPrincipal(claimsIdentity), authProperties);
				HttpContext.Session.SetInt32("adminAccountID", user.ID);
				return RedirectToAction("index", "dashboard", new { area = "admin" });
			}

			ViewBag.ErrorMessage = "Invalid role";
			return NotFound("Account của bạn có Role không hợp lệ, vui lòng thử lại!");
		}

		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync("GetAppointmentStatus");
			return LocalRedirect("/admin");
		}
	}
}

Tester/CodeScene/Dental_Clinic_System/Dental_Clinic_System/Areas/Admin/Views/AdminAccount/Login.cshtml
@{
	ViewData["Title"] = "Login";
	Layout = null;
}

<title>Login</title>
<style>
	*,
	*:before,
	*:after {
		padding: 0;
		margin: 0;
		box-sizing: border-box;
	}

	html {
		font-size: 62.5%;
	}

	body {
		background-color: #e6f6fe;
		font-family: "Baloo Paaji 2", sans-serif;
		font-size: 1.6rem;
	}

	.background {
		width: 430px;
		height: 520px;
		position: absolute;
		transform: translate(-50%, -50%);
		left: 50%;
		top: 50%;
	}

		.background .shape {
			height: 200px;
			width: 200px;
			position: absolute;
			border-radius: 50%;
		}

	.shape:first-child {
		background: linear-gradient(#1845ad, #23a2f6);
		left: -80px;
		top: -80px;
	}

	.shape:last-child {
		background: linear-gradient(to right, #ff512f, #f09819);
		right: -30px;
		bottom: -80px;
	}

	form {
		height: 520px;
		width: 400px;
		background-color: rgba(255, 255, 255, 0.13);
		position: absolute;
		transform: translate(-50%, -50%);
		top: 50%;
		left: 50%;
		border-radius: 10px;
		backdrop-filter: blur(3px);
		border: 2px solid rgba(255, 255, 255, 0.1);
		box-shadow: 0 0 40px rgba(8, 7, 16, 0.6);
		padding: 50px 35px;
	}

		form * {
			letter-spacing: 0.5px;
			outline: none;
			border: none;
		}

		form h1 {
			color: #1376f8;
			font-size: 4rem;
			font-weight: bold;
			line-height: 42px;
			text-align: center;
		}

	label {
		display: block;
		margin-top: 30px;
		font-size: 2.4rem;
		font-weight: bold;
		color: #1376f8;
	}

	input {
		display: block;
		height: 50px;
		width: 100%;
		border-radius: 3px;
		padding: 0 10px;
		margin-top: 8px;
		color: #1376f8;
		font-size: 1.8rem;
		font-weight: 400;
	}

	::placeholder {
		color: #1376f8;
	}

	button {
		margin-top: 50px;
		width: 100%;
		background-color: #1376f8;
		color: #fff;
		padding: 15px 0;
		font-size: 18px;
		font-weight: 600;
		border-radius: 5px;
		cursor: pointer;
	}

		button:hover {
			background-color: #0d5cb6;
		}
</style>

<div class="background">
	<div class="shape"></div>
	<div class="shape"></div>
</div>

<form id="loginForm" asp-controller="AdminAccount" asp-action="Login" method="post">
	<h1>Login</h1>
	@if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
	{
		<p class="error-message">@ViewBag.ErrorMessage</p>
	}
	<label for="username">Username</label>
	<input type="text" id="username" name="username" placeholder="Username" required />
	<label for="password">Password</label>
	<input type="password" id="password" name="password" placeholder="Password" required />
	<input type="hidden" name="returnUrl" value="@ViewBag.ReturnUrl" />
	<button type="submit">Log In</button>

	<p class="error-message" id="error-message"></p>
</form>